### ISSUE TITLE
fix excubia pkg name?

### ISSUE THREAD

**Issue by sripwoud** [privacy-scaling-explorations/zk-kit.solidity#33]
The [`excubiae` contracts package](https://github.com/privacy-scaling-explorations/zk-kit.solidity/blob/202754d36a75200202f4450a1f845049cd30b84d/packages/excubiae/contracts/package.json#L2) is not consistent with those of the other packages: it misses a `.sol` extension.
A [first version is already published though](https://www.npmjs.com/package/@zk-kit/excubiae). Should we rename it for the next versions still?

**Comment by cedoor** [comment]
Hey @sripwoud, excubiae is different from the others because there's no JS implementation. So in theory there's no need to have `.sol`.

Do you think we should still force this rule?

**Comment by sripwoud** [comment]
I personally don't mind. I didn't know if this was a deliberate choice or not.

**Comment by 0xjei** [comment]
> I personally don't mind. I didn't know if this was a deliberate choice or not.

@sripwoud thx for bringing this up - yes, we discussed it with @cedoor a couple of weeks ago. I'm open to whatever btw

**Comment by cedoor** [comment]
Let's keep it without `.sol` then 👍🏽
